### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by shalpern1** [lauraghouzi/WebTech_Project#5]
Technical issues:
1. Favicon - you should add a favicon (the icon on the tab which currently looks like a globe).
2. Each page should have a specific title in the head instead of "Proposal for Website".
3. Perhaps you should center the recipes to make them more visually appealing.
4. Logo not working on desserts page.
5. Search bar not working.

Overall feedback:
Great job with the website so far. I would go a little deeper into the recipes - perhaps the steps to making each one on top of the ingredient list you include. Looking forward to seeing the final product!

**Comment by lauraghouzi** [comment]
Thank you so much for your input!
